### ISSUE TITLE
Dependancies issue

### ISSUE THREAD

**Issue by SophieZaaijer** [mitenjain/nanopore#8]
Hi! 
I tried to compile nanpore and found 2 minor issues: 
1 the git submodules use ssh connection to github can not be publicly accessed. 
if you change them to HTTPS then they could be cloned:
```
[submodule "submodules"]
	path = submodules
	url = https://github.com/benedictpaten/jobTree.git
[submodule "subModules/jobTree"]
	path = subModules/jobTree
	url = https://github.com/benedictpaten/jobTree.git
[submodule "subModules/sonLib"]
	path = subModules/sonLib
	url = https://github.com/benedictpaten/sonLib.git
[submodule "submodules/bwa"]
	path = submodules/bwa
	url = https://github.com/lh3/bwa.git
[submodule "submodules/lastz"]
	path = submodules/lastz
	url = https://github.com/UCSCReconGroup/lastz.git
[submodule "submodules/jobTree"]
	path = submodules/jobTree
	url = https://github.com/benedictpaten/jobTree.git
[submodule "submodules/sonLib"]
	path = submodules/sonLib
	url = https://github.com/benedictpaten/sonLib.git
[submodule "submodules/last"]
	path = submodules/last
	url = https://github.com/UCSCReconGroup/last.git
[submodule "submodules/blasr"]
	path = submodules/blasr
	url = https://github.com/PacificBiosciences/blasr.git
[submodule "submodules/hdf5"]
	path = submodules/hdf5
	url = https://github.com/UCSCReconGroup/hdf5.git
[submodule "submodules/cactus"]
	path = submodules/cactus
	url = https://github.com/benedictpaten/cactus.git
```

2 Building nanopore (or one of its dependancies) requires the Tokyocabinet library. 
On Ubuntu this can be solved with `sudu apt-get install libtokyocabinet-dev`

Thanks! 

kind regards, 
Sophie

**Comment by mitenjain** [comment]
Hi Sophie,

Thank you for your message. 

We will change the ssh connection to use HTTPS, and fix the Tokyocabinet requirement. I also want to direct you to marginAlign (https://github.com/benedictpaten/marginAlign), which is the newer and supported version of nanopore pipeline.

Thank you.
Best regards,
Miten

**Comment by mitenjain** [comment]
Hi Sophie, 

We changed the ssh connection. I Can send a custom suite to you that may not require Tokyocabinet; but would recommend you to use marginAlign pipeline that will be our longterm supported pipeline.

Let me know if you come across any issues.
Best regards,
Miten
